Move the dependency on core.protolog.pb to services
This is the same as Iefdd457e99fc61c1ce2f5a05ae59f5e12256a764 where we
moved the dependency on protolog.conf.json.gz to services.

core.protolog.pb has is causing a dependency cycle reported as below:

error: frameworks/base/services/core/Android.bp:111:1: encountered dependency cycle:
error: frameworks/base/services/core/Android.bp:311:1:     module "core.protolog.pb" variant "android_x86_64" depends on module "checked-core.protolog.pb"
error: frameworks/base/services/core/Android.bp:111:1:     module "checked-core.protolog.pb" depends on module "gen-core.protolog.pb"
error: frameworks/base/services/core/Android.bp:78:1:     module "gen-core.protolog.pb" depends on module "protolog-groups" variant "android_common"
error: frameworks/base/core/java/Android.bp:589:1:     module "protolog-groups" variant "android_common" depends on module "framework" variant "android_common"
error: frameworks/base/Android.bp:542:1:     module "framework" variant "android_common" depends on module "framework-minus-apex" variant "android_common"
error: frameworks/base/Android.bp:486:1:     module "framework-minus-apex" variant "android_common" depends on module "core.protolog.pb" variant "android_x86_64"

Bug: 321626681
Test: check the existence of /system/etc/core.protolog.pb in installed-files.txt
Change-Id: I502eee9e184bcf5fa3e5443cc3c124828ed565ad

Former-commit-id: d80202cc51223b9d5a4caa16857a61f0357e85f2